<option value="52503" {{ isInputChecked($case->$name, '52503', 's')	}}>นพ. กวินท์ รุจิขจรเดช</option>
<option value="45678" {{ isInputChecked($case->$name, '45678', 's')	}}>นพ. กฤษณ์สมภพ เตชะวรุตมะ</option>
<option value="58200" {{ isInputChecked($case->$name, '58200', 's')	}}>นพ. นพดล พิสิฐประภา</option>
<option value="49539" {{ isInputChecked($case->$name, '49539', 's')	}}>พญ. ปวีณา กนกพจนานนท์</option>
<option value="52674" {{ isInputChecked($case->$name, '52674', 's')	}}>นพ. เมธาวุฒิ เข็มมงคล</option>
<option value="48877" {{ isInputChecked($case->$name, '48877', 's')	}}>พญ. อมรรัตน์ คำสร้อย</option>

<option value="46936" {{ isInputChecked($case->$name, '46936', 's')	}}>นพ. กฤช กลั่นสุภา</option>
<option value="47580" {{ isInputChecked($case->$name, '47580', 's')	}}>นพ. กฤษฎา พงศกรกุลชาติ</option>
<option value="44234" {{ isInputChecked($case->$name, '44234', 's')	}}>นพ. เดชาธร รัศมีกุลธนา</option>
<option value="45851" {{ isInputChecked($case->$name, '45851', 's')	}}>พญ. ฐิติยาภรณ์ บุญรับจิรโรจน์</option>
<option value="45895" {{ isInputChecked($case->$name, '45895', 's')	}}>พญ. มถนภรณ์ เคหะลูน</option>
<option value="50426" {{ isInputChecked($case->$name, '50426', 's')	}}>นพ. อนุยุต ตันติภูมิอมร</option>

{{-- <option value="43030" {{ isInputChecked($case->$name, '43030', 's') }}> นพ. ดวิษ จิระวิจิตรกุล</option>
<option value="47668" {{ isInputChecked($case->$name, '47668', 's') }}> พญ. เนสินี เก้าเอี้ยน</option>
<option value="45269" {{ isInputChecked($case->$name, '45269', 's') }}> พญ. ธิดารัตน์ ลักษณานันท์</option>
<option value="44391" {{ isInputChecked($case->$name, '44391', 's') }}> พญ. วณิชยา สมงาม</option>
<option value="47766" {{ isInputChecked($case->$name, '47766', 's') }}> พญ. สลิลทิพย์ เตียวโชคตระกูล</option>
<option value="47805" {{ isInputChecked($case->$name, '47805', 's') }}> พญ. อารีรัตน์ อุณหสุทธิยานนท์</option>

<option value="35793" {{ isInputChecked($case->$name, '35793', 's') }} >นพ.จักรพงษ์ เทศพิทักษ์</option>
<option value="39846" {{ isInputChecked($case->$name, '39846', 's') }} >นพ.อัซฮารี สมาน</option>
<option value="51786" {{ isInputChecked($case->$name, '51786', 's') }} >นพ.อรรถพงศ์ ผ่องพิทักษ์ชัย</option>
<option value="41090" {{ isInputChecked($case->$name, '41090', 's') }} >พญ.ชลลดา เรืองปิ่น</option>
<option value="43150" {{ isInputChecked($case->$name, '43150', 's') }} >พญ.ภัทรนันท์ ปัญญาธรรมรัศมิ</option>
<option value="42240" {{ isInputChecked($case->$name, '42240', 's') }} >พญ.วราภรณ์ เนติกานต์</option>

<option value="38872" {{ isInputChecked($case->$name, '38872', 's') }} >นพ.นราธิป ทองทับ</option>
<option value="41171" {{ isInputChecked($case->$name, '41171', 's') }} >นพ.พัทธดนย์ ศิริวงศ์รังสรร</option>
<option value="45208" {{ isInputChecked($case->$name, '45208', 's') }} >นพ.จิตวัต พูลพุทธพงษ์</option>
<option value="39285" {{ isInputChecked($case->$name, '39285', 's') }} >นพ.ถิรพล สินปรีชานนท์</option>
<option value="41905" {{ isInputChecked($case->$name, '41905', 's') }} >นพ.ธนพล พงศ์นัชชา</option>
<option value="39364" {{ isInputChecked($case->$name, '39364', 's') }} >พญ.มัชฌิมา รอดเชื้อ</option>
<option value="41145" {{ isInputChecked($case->$name, '41145', 's') }} >นพ.นิพนธ์ นครน้อย</option>
<option value="39536" {{ isInputChecked($case->$name, '39536', 's') }} >พญ.ปวิตรา วาสุเทพรังสรรค์ </option>
<option value="36921" {{ isInputChecked($case->$name, '36921', 's') }} >พญ.ดวงนภา จันเทวา</option>
<option value="42661" {{ isInputChecked($case->$name, '42661', 's') }} >พญ.ญาธิป มุกดาลอย</option>
<option value="39374" {{ isInputChecked($case->$name, '39374', 's') }} >พญ.รักษิณา ชัยณรงค์ศิริพร</option>
<option value="42983" {{ isInputChecked($case->$name, '42983', 's') }} >พญ.จงถนอม โตวิเศษ</option>
<option value="37848" {{ isInputChecked($case->$name, '37848', 's') }} >พญ. กรชนก วารีแสงทิพย์</option>
<option value="30836" {{ isInputChecked($case->$name, '30836', 's') }} >พญ. จิดาภา มหามงคลสวัสดิ์</option>
<option value="45208" {{ isInputChecked($case->$name, '45208', 's') }} >นพ. จิตวัติ พูลพุทธพงศ์</option>
<option value="41092" {{ isInputChecked($case->$name, '41092', 's') }} >นพ. ชวลิต โชติเรืองนภา</option>
<option value="39285" {{ isInputChecked($case->$name, '39285', 's') }} >นพ. ถิรพล สินปรีชานนท์</option>
<option value="41905" {{ isInputChecked($case->$name, '41905', 's') }} >นพ. ธนพล พงศ์นัชชา</option>
<option value="33596" {{ isInputChecked($case->$name, '33596', 's') }} >นพ. ธรรมพร เนาว์รุ่งโรจน์</option>
<option value="38872" {{ isInputChecked($case->$name, '38872', 's') }} >นพ. นราธิป ทองทับ</option>
<option value="43065" {{ isInputChecked($case->$name, '43065', 's') }} >พญ. บัณย์ฐิตา ธนภัทรบริสุทธิ์</option>
<option value="41148" {{ isInputChecked($case->$name, '41148', 's') }} >พญ. บุลพร เตชจงนำชัย</option>
<option value="43068" {{ isInputChecked($case->$name, '43068', 's') }} >นพ. ปรัชญา พุมอุทัยวิรัตน์</option>
<option value="43317" {{ isInputChecked($case->$name, '43317', 's') }} >พญ. พัชรินทร์ พิทักษ์โชคชัย</option>
<option value="41171" {{ isInputChecked($case->$name, '41171', 's') }} >นพ. พัทธดนย์ ศิริวงศ์รังสรร</option>
<option value="39364" {{ isInputChecked($case->$name, '39364', 's') }} >พญ. มัชฌิมา รอดเชื้อ</option>
<option value="34508" {{ isInputChecked($case->$name, '34508', 's') }} >พญ. รัชฎา เหมินทร์</option>
<option value="37961" {{ isInputChecked($case->$name, '37961', 's') }} >พญ. รัตติยา เภาทอง</option>
<option value="36732" {{ isInputChecked($case->$name, '36732', 's') }} >นพ. วีรกิจ นาวีระ</option>
<option value="37650" {{ isInputChecked($case->$name, '37650', 's') }} >นพ. สุนทร ปิ่นไพบูลย์</option> --}}
