<select class="form-control" name="{{ $name }}">
    <option selected disabled hidden value=''></option>
    <option value='1' {{ isInputChecked($case->$name,1,'s') }} >AIN | Acute interstitial nephritis</option>
    <option value='5' {{ isInputChecked($case->$name,5,'s') }} >Alport’s syndrome
    <option value='2' {{ isInputChecked($case->$name,2,'s') }} >Amyloidosis
    <option value='3' {{ isInputChecked($case->$name,3,'s') }} >ANCA GN/Pauci-immune GN | Antineutrophil cytoplasmic antibody vasculitis
    <option value='4' {{ isInputChecked($case->$name,4,'s') }} >Anti-GBM | Anti-glomerular basement membrane
    <option value='7' {{ isInputChecked($case->$name,7,'s') }} >APS | Antiphospholipid syndrome
    <option value='6' {{ isInputChecked($case->$name,6,'s') }} >APSN | Antiphospholipid syndrome nephropathy
    <option value='8' {{ isInputChecked($case->$name,8,'s') }} >ATIN | Acute tubulointerstitial nephritis
    <option value='9' {{ isInputChecked($case->$name,9,'s') }} >ATN | Acute tubular necrosis
    <option value='10' {{ isInputChecked($case->$name,10,'s') }} >C3G | C3 glomerulopathy</option>
    <option value='11' {{ isInputChecked($case->$name,11,'s') }} >Cast nephropathy</option>
    <option value='12' {{ isInputChecked($case->$name,12,'s') }} >Cast Nephropathy</option>
    <option value='13' {{ isInputChecked($case->$name,13,'s') }} >CGN | Chronic glomerulonephritis (unclassified)/diffuse sclerosing GN</option>
    <option value='16' {{ isInputChecked($case->$name,16,'s') }} >Chronic pyelonephritis</option>
    <option value='14' {{ isInputChecked($case->$name,14,'s') }} >Combine GN</option>
    <option value='15' {{ isInputChecked($case->$name,15,'s') }} >Cryoglobulinemic GN</option>
    <option value='17' {{ isInputChecked($case->$name,17,'s') }} >CTIN | Chronic tubulointerstial nephritis</option>
    <option value='18' {{ isInputChecked($case->$name,18,'s') }} >DDD | Dense deposit disease</option>
    <option value='20' {{ isInputChecked($case->$name,20,'s') }} >DN + GN | Diabetic nephropathy + Glomerulonephritis</option>
    <option value='19' {{ isInputChecked($case->$name,19,'s') }} >DN | Diabetic nephropathy</option>
    <option value='21' {{ isInputChecked($case->$name,21,'s') }} >ESRD | End-stage renal failure</option>
    <option value='22' {{ isInputChecked($case->$name,22,'s') }} >Fibrillary GN</option>
    <option value='23' {{ isInputChecked($case->$name,23,'s') }} >FSGS | Focal segmental glomerulosclerosis</option>
    <option value='24' {{ isInputChecked($case->$name,24,'s') }} >HCDD | Heavy chain deposit disease</option>
    <option value='25' {{ isInputChecked($case->$name,25,'s') }} >HIVAN | HIV-associated nephropathy</option>
    <option value='26' {{ isInputChecked($case->$name,26,'s') }} >HSP | Henoch-Schönlein purpura</option>
    <option value='27' {{ isInputChecked($case->$name,27,'s') }} >HTN | Hypertension</option>
    <option value='28' {{ isInputChecked($case->$name,28,'s') }} >Idiopathic Crescentic GN</option>
    <option value='29' {{ isInputChecked($case->$name,29,'s') }} >IgAN | Immunoglobulin A nephropathy</option>
    <option value='30' {{ isInputChecked($case->$name,30,'s') }} >IgMN | Immunoglobulin M nephropathy</option>
    <option value='56' {{ isInputChecked($case->$name,56,'s') }} >Inadequate/Non diagnostic</option>
    <option value='31' {{ isInputChecked($case->$name,31,'s') }} >LCDD | Light chain deposit disease</option>
    <option value='32' {{ isInputChecked($case->$name,32,'s') }} >LN | Lupus nephritis</option>
    <option value='33' {{ isInputChecked($case->$name,33,'s') }} >LN I | Lupus nephritis class I</option>
    <option value='34' {{ isInputChecked($case->$name,34,'s') }} >LN II | Lupus nephritis class II</option>
    <option value='35' {{ isInputChecked($case->$name,35,'s') }} >LN III | Lupus nephritis class III</option>
    <option value='36' {{ isInputChecked($case->$name,36,'s') }} >LN III+V | Lupus nephritis class III+V</option>
    <option value='37' {{ isInputChecked($case->$name,37,'s') }} >LN IV | Lupus nephritis class IV</option>
    <option value='38' {{ isInputChecked($case->$name,38,'s') }} >LN IV+V | Lupus nephritis class IV+V</option>
    <option value='39' {{ isInputChecked($case->$name,39,'s') }} >LN V | Lupus nephritis class V</option>
    <option value='40' {{ isInputChecked($case->$name,40,'s') }} >LN VI | Lupus nephritis class VI</option>
    <option value='41' {{ isInputChecked($case->$name,41,'s') }} >MCD | Minimal change disease</option>
    <option value='46' {{ isInputChecked($case->$name,46,'s') }} >Mesangial proliferation</option>
    <option value='45' {{ isInputChecked($case->$name,45,'s') }} >MN | Membranous nephropathy</option>
    <option value='42' {{ isInputChecked($case->$name,42,'s') }} >MPGN type I | Membranoproliferative glomerulonephritis type I</option>
    <option value='43' {{ isInputChecked($case->$name,43,'s') }} >MPGN type II | Membranoproliferative glomerulonephritis type II</option>
    <option value='44' {{ isInputChecked($case->$name,44,'s') }} >MPGN type III | Membranoproliferative glomerulonephritis type III</option>
    <option value='47' {{ isInputChecked($case->$name,47,'s') }} >Nodular sclerosis</option>
    <option value='57' {{ isInputChecked($case->$name,57,'s') }} >Other</option>
    <option value='48' {{ isInputChecked($case->$name,48,'s') }} >Pauli-Immune GN</option>
    <option value='49' {{ isInputChecked($case->$name,49,'s') }} >Post infectious GN/Post streptococcal GN</option>
    <option value='50' {{ isInputChecked($case->$name,50,'s') }} >Renal atheroembolic/Cholesterol emboli</option>
    <option value='51' {{ isInputChecked($case->$name,51,'s') }} >Sclerodermal renal crisis</option>
    <option value='52' {{ isInputChecked($case->$name,52,'s') }} >TBM | Thin basement membrane </option>
    <option value='53' {{ isInputChecked($case->$name,53,'s') }} >TMA | Thrombotic microangiopathy</option>
    <option value='54' {{ isInputChecked($case->$name,54,'s') }} >TTP | Thrombotic thrombocytopenic purpura</option>
    <option value='55' {{ isInputChecked($case->$name,55,'s') }} >Unclassified glomerulonephritis</option>
</select>